# Generated by Django 4.2.4 on 2023-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0003_groupmessage_delete_gmessage_otomessage_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='otomessage',
            name='chat',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat', to='direct.groupmessage'),
        ),
        migrations.AddField(
            model_name='onetoonechat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat', to='direct.otomessage'),
        ),
    ]
