# Generated by Django 4.2.4 on 2023-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Blocked_Friends',
            field=models.ManyToManyField(blank=True, related_name='Blocked_by', to='Accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Restriced_Friends',
            field=models.ManyToManyField(blank=True, related_name='restriced_by', to='Accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Used_to_be_Friends',
            field=models.ManyToManyField(blank=True, related_name='was_friends_with', to='Accounts.profile'),
        ),
    ]
