# Generated by Django 4.2.4 on 2023-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Default_pfp.jpg', null=True, upload_to='pics/pfp_image'),
        ),
    ]
