# Generated by Django 4.2.4 on 2024-01-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_customuser_last_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
