# Generated by Django 4.2.4 on 2024-01-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='activity_status',
            field=models.BooleanField(default=True),
        ),
    ]
